### ISSUE TITLE
Ligand file name error in win64

### ISSUE THREAD

**Issue by zjujdj** [lucagl/MOAD_ligandFinder#3]
hello, the lfetch.py script in the windows system would generate illegal Ligand file name (could occur colon in the file name) and therefore cannot extrat the ligand corretly. But it runs perfectly in linux, see below:

# windows 10, 64
(gpu02_py) G:\05Coding\GNN_DTI-master\dpi_v4\pretrain\MOAD_ligandFinder-1.1>python lfetch.py
Insert pdb name
1FWE
Valid ligands found:  1
Excluded: 0
Ligands: ['HAE_C:989']
Insert pdb name

# linux
(/home/dejun/work_spaces/py/conda_env/py365) [dejun@mu01 MOAD_ligandFinder-main]$ python lfetch.py 
Insert pdb name 
1FWE
Valid ligands found:  1
Excluded: 0
Ligands: ['HAE_C989']
Insert pdb name

**Comment by lucagl** [comment]
Hi,

Thank you for your feedback.
Are you running the latest version? When did you clone/copied the code ? 
Indeed, I already noticed this problem and from the last commit the colon character was suppressed in the ligand naming scheme..

**Comment by zjujdj** [comment]
Sorry, bro...i downloaded the latest codes, and no such issue was found!

**Comment by lucagl** [comment]
No worries. I'm glad it's working.

**Comment by zjujdj** [comment]
Thank you very much, bro! This script helps me a lot!!!
